### PR TITLE
Failed Update Dashboard

### LINKED ISSUE #217: Download failed updates
Admins need to be able to download all the data regarding books that failed to update as a csv

### LINKED ISSUE #218: Fix overscroll bug on admin dashboard
The scroll over flow is causing the infinite scroll to not get triggered unless the user over scrolls.

### PR DESCRIPTION
**Pull request by varunrau**
This pull request adds infinite scroll and fixes the nil asin problem.

Fixes #217 
Fixes #218

### CODE REVIEW

File: app/models/book.rb [hunk 1]
```diff
@@ -151,6 +151,10 @@ def url
     "http://www.amazon.com/dp/" + asin
   end
 
+  def asin
+    read_attribute(:asin) || ""
```
Comment (varunrau) [inline app/models/book.rb]: wow thanks hound! This one was actually useful!! hound ++

File: app/assets/javascripts/react_components/admin_dashboard/book_statuses.js.jsx [hunk 2]
```diff
@@ -3,10 +3,17 @@
 var BookStatusView = React.createClass({
   getInitialState: function() {
     return {
-      books: []
```
Comment (varunrau) [inline app/assets/javascripts/react_components/admin_dashboard/book_statuses.js.jsx]: don't need this here and in `componentDidMount`

File: app/assets/javascripts/react_components/admin_dashboard/book_statuses.js.jsx [hunk 3]
```diff
@@ -19,6 +26,37 @@ var BookStatusView = React.createClass({
...
+  },
+  downloadFaildUpdateReport: function() {
+    $.ajax({
+      url: "/admin/dashboard/failed_report",
+      type: "GET",
+      success: function(data) {
+        window.open("data:text/csv;charset=utf-8," + escape(data));
+      }.bind(this),
+      error: function(xhr, status, error) {
+        toastr.error("There was an error while generating the report");
```
Comment (varunrau) [inline app/assets/javascripts/react_components/admin_dashboard/book_statuses.js.jsx]: add period

File: app/assets/javascripts/react_components/admin_dashboard/book_statuses.js.jsx [hunk 4]
```diff
@@ -29,20 +67,37 @@ var BookStatusView = React.createClass({
     return (
       <div  className="container">
         <div className="panel panel-primary">
-          <div className="row">
```
Comment (varunrau) [inline app/assets/javascripts/react_components/admin_dashboard/book_statuses.js.jsx]: interesting this was a poor diff

File: app/assets/javascripts/react_components/react-infinite-scroll.js [hunk 5]
```diff
@@ -26,9 +26,7 @@ var InfiniteScroll = React.addons.InfiniteScroll = React.createClass({
     return React.DOM.div(null, props.children, props.hasMore && (props.loader || InfiniteScroll._defaultLoader));
   },
   scrollListener: function () {
-    var el = this.getDOMNode();
-    var scrollTop = (window.pageYOffset !== undefined) ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
-    if (topPosition(el) + el.offsetHeight - scrollTop - window.innerHeight < Number(this.props.threshold)) {
+    if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
```
Comment (varunrau) [inline app/assets/javascripts/react_components/react-infinite-scroll.js]: I think I could bring this back since fixing #218

File: app/controllers/admin/dashboard_controller.rb [hunk 6]
```diff
@@ -84,6 +84,15 @@ def get_number_purchases
     render text: User.find(params[:id]).purchases.where(is_approved: nil, is_purchased: true).count
   end
 
+  def generate_failed_report
+    failed_books = FailedUpdate.all.map do |update|
```
Comment (varunrau) [inline app/controllers/admin/dashboard_controller.rb]: good call

File: app/controllers/admin/dashboard_controller.rb [hunk 7]
```diff
@@ -84,6 +84,15 @@ def get_number_purchases
...
+      update.book
+    end
+    send_data Book.to_csv(failed_books),
+      type: 'text/csv; charset=iso-8859-1; header=present',
```
Comment (varunrau) [inline app/controllers/admin/dashboard_controller.rb]: not bad advice either

Comment (varunrau) [inline app/controllers/admin/dashboard_controller.rb]: but single quotes make @SamLau95 happy

File: app/controllers/api/v1/books_controller.rb [hunk 8]
```diff
@@ -1,8 +1,9 @@
 class Api::V1::BooksController < ApplicationController
 
   def index
-    # TODO replace with infinite scroll
```
Comment (varunrau) [inline app/controllers/api/v1/books_controller.rb]: DONE

**Comment by varunrau** [comment]
LGTM

**Comment by varunrau** [comment]
LATM
