### PR TITLE
Varun/failed update dashboard

### LINKED ISSUE #134: Add Amazon crashes report
Add a tab to the admin dashboard that reports when a book is no longer available on amazon (ie. when the asin lookup fails)

### PR DESCRIPTION
**Pull request by varunrau**
Adds amazon crash report status to admin dashboard.

TODO: need to update page to infinite scroll.
Fixes #134

### CODE REVIEW

File: app/assets/javascripts/react_components/admin_dashboard/admin_dashboard.js.jsx [hunk 1]
```diff
@@ -449,9 +449,8 @@ var DashboardTabDisplay = React.createClass({
       );
     } else if (this.props.type == tabs.VIEWBOOKS) {
       return (
-        <div>
-          View Books
-        </div>
+        // <div> hi</div>
```
Comment (varunrau) [inline app/assets/javascripts/react_components/admin_dashboard/admin_dashboard.js.jsx]: remove

**Comment by varunrau** [comment]
LGTM
